// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGmO8PMYPgPJhjqD3EkH-9iClOmVdJhOc',
    appId: '1:668208061826:web:e3be12b07164ffbd11839b',
    messagingSenderId: '668208061826',
    projectId: 'flutter-task-management-f96f2',
    authDomain: 'flutter-task-management-f96f2.firebaseapp.com',
    storageBucket: 'flutter-task-management-f96f2.firebasestorage.app',
    measurementId: 'G-1LVVG2QYJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6l8zE-qckO6-__c1guah5PtyF1dbjn5E',
    appId: '1:668208061826:android:3862ab7b8251dc4d11839b',
    messagingSenderId: '668208061826',
    projectId: 'flutter-task-management-f96f2',
    storageBucket: 'flutter-task-management-f96f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYLj5GHyqd72E4TC88TFLbLg3ytHXTr3U',
    appId: '1:668208061826:ios:69c4c42dac52a17a11839b',
    messagingSenderId: '668208061826',
    projectId: 'flutter-task-management-f96f2',
    storageBucket: 'flutter-task-management-f96f2.firebasestorage.app',
    iosBundleId: 'com.example.cw03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYLj5GHyqd72E4TC88TFLbLg3ytHXTr3U',
    appId: '1:668208061826:ios:69c4c42dac52a17a11839b',
    messagingSenderId: '668208061826',
    projectId: 'flutter-task-management-f96f2',
    storageBucket: 'flutter-task-management-f96f2.firebasestorage.app',
    iosBundleId: 'com.example.cw03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGmO8PMYPgPJhjqD3EkH-9iClOmVdJhOc',
    appId: '1:668208061826:web:42678d0448a2b90611839b',
    messagingSenderId: '668208061826',
    projectId: 'flutter-task-management-f96f2',
    authDomain: 'flutter-task-management-f96f2.firebaseapp.com',
    storageBucket: 'flutter-task-management-f96f2.firebasestorage.app',
    measurementId: 'G-PWPW9DPLM0',
  );
}
